apiVersion: apps/v1
kind: Deployment
metadata:
  name: exhibition-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exhibition
  template:
    metadata:
      labels:
        app: exhibition
    spec:
      containers:
        # Izbrati moras zadnji tag
        - image: rsogalerija/exhibition:1.0.0-SNAPSHOT-3.1
          name: exhibition
          env:
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://kandula.db.elephantsql.com:5432/bbdvsbvr
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: bbdvsbvr
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              value: B3LybuFNngaveFG9mrUVfD_NjDzl1AIP
              #valueFrom:
              #  secretKeyRef:
              #    name: pg-pass
              #    key: KUMULUZEE_DATASOURCES0_PASSWORD
          ports:
            - containerPort: 8080
              name: server
              protocol: TCP


---

apiVersion: v1
kind: Service
metadata:
  name: exhibition
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: server
  selector:
    app: exhibition